POSTGRES_USERNAME=udagrambtdev
POSTGRES_PASSWORD=udagrambtdev
POSTGRES_DB=udagrambtdev
POSTGRES_HOST=udagrambtdev.cvnytmcypfhy.us-east-1.rds.amazonaws.com

AWS_BUCKET=udacity-project-ms

JWT_SECRET=helloworld

AWS_REGION=us-east-1
AWS_PROFILE=default

PORT=8080